server {
    listen 80;
    server_name _;

    root /var/www/tian-system/public;
    index index.php index.html;

    client_max_body_size 520m;

    access_log /var/log/nginx/tian-system.access.log;
    error_log /var/log/nginx/tian-system.error.log;

    location / {
        try_files $uri /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.1-fpm.sock;
    }

    location ~ /\.(?!well-known) {
        deny all;
    }

    location ~ ^/(storage|deploy|\.github|\.git) {
        deny all;
    }
}
